### ISSUE TITLE
Remove `max_val` input from thresholding functions

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1194]
**Is your feature request related to a problem? Please describe.**
Right now most of the `pcv.threshold.` function have an input parameter with the default value set to 255, which is the pixel intensity for the "kept" pixels in a binary mask. Instead, we want this default behavior to be the constant behavior.

**Describe the solution you'd like**
Set `max_val` directly within the function. Make separate Pull Requests, and base them on the release-4.0 branch (NOT main). 

1. remove the parameter from the `function.py` file 
2. update the respective tests (remove parameter) 
3. update the respective doc page `function.md`
4. update the `updating.md` doc page to reflect the new syntax

**Functions with Instances of `max_val`**
- [x] plantcv.threshold.binary(gray_img, threshold, max_value, object_type="light") --> @afinit #1210 
- [x] plantcv.threshold.mean(gray_img, max_value, object_type="light") --> @afinit #1212 
- [x] plantcv.threshold.otsu(gray_img, max_value, object_type="light")--> @afinit #1213
- [x] plantcv.threshold.gaussian(gray_img, max_value, object_type="light")--> @afinit #1214 
- [x] plantcv.threshold.texture_filter(gray_img, ksize, threshold, offset=3, texture_method='dissimilarity', borders='nearest', max_value=255)--> @afinit #1219
- [x] plantcv.threshold.triangle(gray_img, max_value, object_type="light", xstep=1)--> @afinit #1218
- [x] helper function `_call_threshold` --> @afinit #1220 
- [x] helper function `_call_adaptive_threshold` --> @afinit #1221 
- [x] plantcv.threshold.dual_channels --> @afinit #1224 

**Documentation updates only**
- [x] `within_frame.md`
- [x] `hyperspectral_tutorial.md`
- [x] `psII_tutorial.md` 

**Additional context**
In sci-kit image, binary masks contain 0 (black) pixels and 1 (white) pixels. The rest of the python computer vision packages typically use 0 / 255 instead. We don't actually want people to change this value though, and I've seen people that treat that input parameter like an upper threshold as if they could splice out just intermediate values in their workflow which indicates it's more confusing than helpful at this point.  

`pcv.visualize.pseudocolor` has a `max_value` parameter but we actually want to keep that one since it's truly doing an upper-limiting function.

**Comment by afinit** [comment]
@HaleySchuhl i think `plantcv.threshold.texture_filter` is supposed to be `plantcv.threshold.texture`

In the `updating.md` file, it's also listed as `texture_filter`, but it looks like it has always been `texture` in the code. Should I update `updating.md` to say `texture` for this one?

Second question: i see a `plantcv.threshold.dual_channels()` with a max_value . do we want to update that function as well?

**Comment by afinit** [comment]
after removing this param from each of the methods here, also remove from the helper method

based on this thread: https://github.com/danforthcenter/plantcv/pull/1210#discussion_r1247917571

**Comment by nfahlgren** [comment]
Heads up that we had `plantcv.threshold.dual_channels` missing from the checklist above
