### ISSUE TITLE
Tutorial Updates &  other July 20, 2023 Hack-a-thon Day Tasks

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1293]
# To Do list
Check off an issue once the Pull Request is merged in. To assign yourself to an issue, edit this section and add your name beside the issue. Also assign yourself in the issue which is linked. Once you open a PR, add a tag to it as well. 

- [x] Documentation updates for `max_value` removal, really just within_frame.md since tutorials will be updated significantly and separately  #1194
- [x] Missing documentation page `tabulate_bayes`  #1227 --> #1318 
- [x] Deprecate `get_nir` #1232 --> @HaleySchuhl #1294
- [x] Deprecate hyperspectral.analyze_spectral #945 --> @HaleySchuhl  #1295

# Tutorial Updates
## VIS
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/vis_tutorial/ --> done by @kmurphy61 and ready for review
- [x] https://github.com/danforthcenter/plantcv-tutorial-v4-VIS-single-plant
- [x] PR: #1303
## Thermal
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/thermal_tutorial/ --> @lacostag & Haley finishing
- [x] https://github.com/danforthcenter/plantcv-tutorial-thermal
- [x] PR:  #1302
## VIS-NIR
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/vis_nir_tutorial/  --> @leowlima & Haley finishing up 
- [x] https://github.com/danforthcenter/plantcv-tutorial-vis-nir
- [x] PR: #1301
## Grayscale
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/nir_tutorial/  NIR tutorial (rename/rebrand as a grayscale tutorial) --> @HaleySchuhl 
- [x] https://github.com/danforthcenter/plantcv-tutorial-grayscale
- [x] PR: #1300 
## Photosynthesis
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/psII_tutorial/ --> @kmurphy61 in progress, may wait until psII is updated for final version
- [x] https://github.com/danforthcenter/plantcv-tutorial-photosynthesis 
- [x] PR: #1336
## Hyperspectral
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/hyperspectral_tutorial/ --> @maliagehan 
- [x] https://github.com/danforthcenter/plantcv-tutorial-hyperspectral
- [x] PR: #1313
## Machine learning
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/machine_learning_tutorial/ --> @HaleySchuhl 
- [x] github.com/danforthcenter/plantcv-tutorial-machine-learning
- [x] #1306
## Multi-plant
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/multi-plant_tutorial/ this one is highly outdated, we have deprecated a handful of the multi-plant analysis methods that have been improved upon. Evaluate if this tutorial is still helpful. --> done by @kmurphy61 and ready for review
- [x] https://github.com/danforthcenter/plantcv-tutorial-v4-multiobject
- [x] PR: #1305
## Seeds
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/seed_analysis_tutorial/ -->  @Stylopidae1793 
- [x] https://github.com/danforthcenter/plantcv-tutorial-seeds
- [x] PR: #1316 
## Morphology
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/morphology_tutorial/  : this one has a more detailed tutorial using sorghum [here](https://plantcv.readthedocs.io/en/latest/tutorials/sorghum_morphology_tutorial/) and they are so similar that it might be better to combine and then credit all 3 contributors. @joshqsumner
- [x] https://github.com/danforthcenter/plantcv-tutorial-morphology
- [x] PR: #1308 
## Color correction
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/transform_color_correction_tutorial/ --> @nfahlgren 
- [x] https://github.com/danforthcenter/plantcv-tutorial-color-correction --> @HaleySchuhl 
- [ ] PR:  https://github.com/danforthcenter/plantcv/pull/1339 #1339 
## Input/Output
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/input_output_tutorial/ : believe this one is significantly outdated but the goal is to show off various ways to read in different types of image data and ways to save out data. This "methods of saving out data" is actually a recent topic of discussion and involved append vs overwriting behaviors in CSV vs JSON. --> @joshqsumner 
- [x] https://github.com/danforthcenter/plantcv-tutorial-input-output
- [x] PR:  #1311
## Thresholding
- [ ] https://plantcv.readthedocs.io/en/latest/tutorials/threshold_tutorial/ --> @zeeuqsze 
- [ ] https://github.com/danforthcenter/plantcv-tutorial-threshold
- [ ] PR: 
## ROIs
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/roi_tutorial/ --> use the multi-plant tutorial by @kmurphy61 as a template, uses point-and-click ROIs, grid ROIs, need to add other shapes, partial vs. cutto to a roi_tutorial
- [x] https://github.com/danforthcenter/plantcv-tutorial-roi --> @HaleySchuhl 
- [ ] PR: #1339 

## Watershed
- [x] https://plantcv.readthedocs.io/en/latest/tutorials/watershed_segmentation_tutorial/ --> @maliagehan 
- [x] https://github.com/danforthcenter/plantcv-tutorial-watershed
- [x] PR: #1298 

## Exist in v3 and need updating
- [x] Arabidopsis Multi-Plant Workflow (template?) [¶](https://plantcv.readthedocs.io/en/release-4.0/tutorials/arabidopsis_multi_plant_tutorial/) - https://github.com/danforthcenter/plantcv/pull/1338
    - [x] still has `max_value` in threshold function, could this be our first "template"? 
    - [x] yea still has `pcv.find_objects` so needs updating to v4 totally 
- [ ] HOMOLOGY https://plantcv.readthedocs.io/en/release-4.0/tutorials/homology_tutorial/
    - [x] tutorial 1
    - [x] tutorial 2
    - [x] tutorial 3 
    - [x] tutorial 4
    - [ ] docs update https://github.com/danforthcenter/plantcv/pull/1339

## Don't live in the tutorial gallery yet and need to be added (after v4 release)
- [ ] https://github.com/danforthcenter/plantcv-tutorial-segment-image-series
- [ ] https://github.com/danforthcenter/plantcv-interactive-tutorials
- [ ] https://github.com/danforthcenter/plantcv-tutorial_leaf_instance_segmentation

### User tutorials
- [x] https://github.com/danforthcenter/plantcv-homology-tutorials
- [ ] Rice chalkiness
- [ ] https://github.com/danforthcenter/plantcv-tasselyzer-tutorial
- [ ] https://github.com/danforthcenter/plantcv-tutorial-interactive-pollent-count
- [ ] https://github.com/danforthcenter/plantcv-stomata-tutorial @kmurphy61 will update to be v4

**Comment by HaleySchuhl** [comment]
@kmurphy61 we just merged the changes to PSII that rename light and dark frames. Just say the word and I can update the Photosynthesis tutorial if you'd like, but I'm working under the assumption you'd want to update them 🥇

**Comment by nfahlgren** [comment]
I updated the notebook locally today to make the workshop notebook, so I can push those changes later
