### ISSUE TITLE
PlantCV 4.0 release

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv#1304]
## PlantCV 4.0 release

Goal: release PlantCV 4.0 by Friday, July 28th

### To Do
- [x] Update tutorials and incorporate them into the tutorial gallery #1293
- [x] Add documentation for `tabulate_naive_bayes` #1318 
- [x] Finish removing references to `max_value` for thresholding #1194 @HaleySchuhl 
- [x] Review/revise analysis approaches and other larger docs pages for updates #945
    - [x] Review/revise contribution guide -> #1299 
    - [x] review/revise `updating.md` -> #1324 
    - [x] review/revise `installation.md` -> #1332
- [x] update "block" to `ksize` in the thresholding functions.-> @HaleySchuhl 
    - gaussian, mean,  _call_adaptive_threshold -> #1325 
- [x] Revise photosynthesis dataset naming #1309 @nfahlgren 
- [x] Merge PAM PR #1217 @nfahlgren 
- [x] Change CSV output formats: #1335
- [x] Replace license: #1334

cc @HaleySchuhl
