### ISSUE TITLE
Brainstorming Top Tasks 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1345]
**Tasks we would like to see done and could be contributed by a non-software engineer **
- [x] Add link from tutorial documentation to source code 
    - [x] arabidopsis multiplant (/plantcv/docs/tutorials/arabidopsis_multi_plant_tutorial.md) https://github.com/danforthcenter/plantcv/pull/1348 
    - [x]  (/plantcv/docs/tutorials/grayscale_tutorials.md) 
    - [x] (/plantcv/docs/tutorials/homology_tutorial.md)
    - [x] (/plantcv/docs/tutorials/hyperspectral_sfm_tutorial.md)
    - [x] (/plantcv/docs/tutorials/hyperspectral_tutorial.md)
    - [x] (/plantcv/docs/tutorials/input_output_tutorial.md)
    - [x] (/plantcv/docs/tutorials/machine_learning_tutorial.md)
    - [x] (/plantcv/docs/tutorials/morphology_tutorial.md)
    - [x] (/plantcv/docs/tutorials/multi-plant_tutorial.md)
    - [x] (/plantcv/docs/tutorials/psII_tutorial.md)
    - [x] (/plantcv/docs/tutorials/roi_tutorial.md)
    - [x] (/plantcv/docs/tutorials/seed_analysis_tutorial.md)
    - [x] (/plantcv/docs/tutorials/thermal_tutorial.md)
    - [x] (/plantcv/docs/tutorials/threshold_tutorial.md)
    - [x] (/plantcv/docs/tutorials/transform_color_correction_tutorial.md)
    - [x] (/plantcv/docs/tutorials/vis_nir_tutorial.md)
    - [x] (/plantcv/docs/tutorials/vis_tutorial.md)
    - [x] (/plantcv/docs/tutorials/watershed_segmentation_tutorial.md)
- [x] Color card finding updated algorithm ? https://github.com/danforthcenter/plantcv/issues/1156
- [x] Colab links for tutorials ?
- [ ] Update https://docs.google.com/spreadsheets/d/1gk5VocBA-63gyF_vA6yPNvWreZ1R7-_z4vOfm37YBl8/edit#gid=0 
    - Moving to new issue #1378 
- [x] https://app.deepsource.com/gh/danforthcenter/plantcv/issues?category=recommended&page=1
- [x] The tutorial repos can all be updated to install `plantcv` 4.0 in requirements.txt, we no longer need to clone the GitHub repo
- [x] https://github.com/danforthcenter/plantcv/issues/1349
