### ISSUE TITLE
Relatively Approachable Deepsource Issues 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1382]
**Is your feature request related to a problem? Please describe.**
We wish to tackle the open Deepsource issues in PlantCV and can assign various issues (as not to duplicate work) here. 

https://app.deepsource.com/gh/danforthcenter/plantcv 

- [x] [One-line docstring should fit on one line with quotes](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-D200/occurrences?listindex=0) --> @kmurphy61 #1393
- [x] [No blank lines allowed after function docstring FLK-D202](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-D202/occurrences?listindex=0) --> @joshqsumner #1391
- [x] [No whitespaces allowed surrounding docstring text FLK-D210](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-D210/occurrences?listindex=0) --> @zeeuqsze #1392
- [x] [1 blank line required after class docstring FLK-D204](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-D204/occurrences?listindex=0) --> @AFis-245 #1397
- [x] [Misplaced comparison constant PYL-C2201](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-C2201/occurrences?listindex=0) --> @joshqsumner #1394
- [x] [Imports from same package are not grouped PYL-C0412](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-C0412/occurrences?listindex=0) --> @joshqsumner #1396
- [x] [Line too long FLK-E501 and Multiple blank lines detected at end of the file
FLK-W391](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-E501/occurrences?listindex=0)  --> @joshqsumner #1398
- [x] [Continuation line over-indented for visual indent FLK-E127](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-E127/occurrences?listindex=0) --> @joshqsumner #1400
- [x] [Missing whitespace after ,, ;, or : FLK-E231](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-E231/occurrences?listindex=0) @dhiraj-ms #1399
- [x] [Too many leading # for block comment FLK-E266](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-E266/occurrences?listindex=0) @dhiraj-ms #1402
- [x] [Expected 2 blank lines FLK-E302 ](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/FLK-E302/occurrences?listindex=0) --> @joshqsumner #1401
- [x] [Useless inheritance from object PYL-R0205 ](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-R0205/occurrences?listindex=0) --> @joshqsumner #1403
- [x] [Variable assigned to itself PYL-W0127](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-W0127/occurrences?listindex=0) --> @zeeuqsze #1404
- [x] [Consider removing the commented out code block](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PY-W0069/occurrences?listindex=0) --> @joshqsumner #1406
- [x] [Imported name is not used anywhere in the module PY-W2000](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PY-W2000/occurrences?listindex=0)  @dhiraj-ms #1407
- [x] [Bad comparison test PTC-W0023](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PTC-W0023/occurrences?listindex=0) (nothing showing up to address)
- [x] [Function contains unused argument PYL-W0613](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-W0613/occurrences?listindex=0) --> @zeeuqsze #1405 
- [x] [Unused variable found PYL-W0612](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PYL-W0612/occurrences?listindex=0) --> @HaleySchuhl  #1395
- [x] [Consider using literal syntax to create the data structure PTC-W0019
](https://app.deepsource.com/gh/danforthcenter/plantcv/issue/PTC-W0019/occurrences?listindex=0) --> @zeeuqsze #1408

**Additional context**
Add any other context, sample data, or code relevant to the feature request here.

**Comment by HaleySchuhl** [comment]
Thanks all!
