### ISSUE TITLE
Updates related Size Markers 

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1387]
**Start a discussion about anything you would like**
The standard way to handle size markers has changed over the years and has made `pcv.report_size_marker` a bit outdated. The `params.sample_label` now enables us to use `pcv.analyze.size` to store size marker data that way without overwriting another instance of size traits. We've done some testing recently to check the validity of using the known size of a color card chip, and this has a benefit because people don't have to put another size marker in the image, and concerns about consistency are less constrained with the new `pcv.transform.detect_color_card`. The following tasks are needed to document the change in this supported analysis approach.

- [ ] Document an example of how to use chip size for scaling, maybe in analysis_approach.md 
- [ ] Document an example of using a ruler in the image and the interactive `Points` tool to create a custom measurement (add_observation) 
- [ ] Add a deprecation warning to `pcv.report_size_marker` and plan on removing this function from the codebase in v5 and link to the new method from the documentation page so steer people otherwise if they google "size marker" 
- [ ] Update at least one tutorial to use `detect_color_card` once #1362 is merged in. 
- [ ] Eventually erase mention of `find_color_card` and `report_size_marker`

**Comment by HaleySchuhl** [comment]
discuss/brainstorm a process improvement about the deprecation of `pcv.report_size_marker` and how we handle image level metadata. I think we need to start recording size marker and color card chip sizes (markers) as metadata rather than observations. It makes the data easier to use downstream for size standardization. Maybe detected color card deviance from standard too?
