### ISSUE TITLE
Update `pcv.segment_image_series` and tutorial

### ISSUE THREAD

**Issue by HaleySchuhl** [danforthcenter/plantcv#1569]
**Is your feature request related to a problem? Please describe.**
We have a temporary workaround for now, but we ought to update [`pcv.semgent_image_series`](https://github.com/danforthcenter/plantcv/issues/1568) to handle the v4 syntax of multi-object ROIs (e.g. `Objects` class). 

**Describe the solution you'd like**
- [ ] Update `pcv.semgent_image_series` to accept the output from `pcv.roi.multi` in the roi input parameter
- [ ] Update the documentation so that it's clear this can be used on one time series at a time 
- [ ] Update the tutorial [here](https://github.com/danforthcenter/plantcv-tutorial-segment-image-series) based on the new syntax
- [ ] And finally, add the updated tutorial to the PlantCV gallery of tutorials (add all the buttons, and add a link to the tutorial from the function documentation page. 

**Describe alternatives you've considered**
Document the workaround. 

**Additional context**
https://github.com/danforthcenter/plantcv/issues/1568
